#!/bin/bash

# Copyright 2013 Florian Bruhin <me@the-compiler.org>
# Manages SSH-tunnels via systemd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>. 

config="/etc/sshtunnel.conf"

# Gets a config section from the config
# $1: name of the section
conf_section() {
    (( $# < 1 )) && return 2
    [[ -f "$config" && -r "$config" ]] || return 3
    unset secstart
    while read line; do # No -r by intention
        line="${line%%[;#]*}" # Strip inline comments
        [[ -z "$line" ]] && continue
        if [[ "$secstart" ]]; then
            [[ "$line" == '['*']' ]] && return 0 # End of a section
            echo "$line"
        fi
        [[ "$line" == "[$1]" ]] && secstart=1 # Start of a section
    done < "$config"
    [[ "$secstart" ]] && return 0 || return 1
}

# Gets a value of a key from the config
# $1: name of the section
# $2: name of the key
conf_key() {
    (( $# < 2 )) && return 2
    conf_section "$1" "$3" | while read -r line; do
        key="${line%%=*}"
        val="${line#*=}"
        [[ "$key" == "$2" ]] && echo "$val" && return 0
    done
    return 1
}

# Prints an error message and exits
# $1: message
# $2: exit code (optional)
die() {
    echo "$1" >&2
    exit "${2:-0}"
}

while :; do
    case "$1" in
        -c | --config)
            config="$2"
            shift 2
            ;;
        --) # End of all options
            shift
            break
            ;;
        -*)
            die "Unknown option: $1"
            ;;
        *) # All parameters shifted
            break
            ;;
    esac
done
